services:
  - type: web
    name: telegram-bot
    env: docker
    repo: https://github.com/tomson20/Sales-bot--telegram
    branch: master
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: შენის ტოკენი
      - key: ADMIN_CHAT_ID
        value: შენი Chat ID
      - key: SPREADSHEET_ID
        value: შენი spreadsheet ID
    autoDeploy: true
